version: '3.7'

services:
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "BoojuxMinioAdmin"
      MINIO_ROOT_PASSWORD: "Boojux221010"
    command: server --console-address ":9001" /data

volumes:
  minio_data:

